env:
  _target_: capx.envs.tasks.franka.franka_libero_env.FrankaLiberoCodeEnv
  cfg:
    _target_: capx.envs.tasks.base.CodeExecEnvConfig
    low_level:
      _target_: capx.envs.simulators.libero.FrankaLiberoEnv
      suite_name: libero_object
      task_id: 6
      privileged: false
      max_steps: 8000
      control_freq: 20
    privileged: false
    apis:
      - FrankaLiberoApi
